import type { Metadata } from "next";
import Link from "next/link";
import { PageHero } from "@/components/page-hero";
import { CtaBand } from "@/components/cta-band";
import { isExternalWhatsApp, whatsappHref } from "@/lib/site";

export const metadata: Metadata = { title: "Pharmacy Services", description: "Explore prescription, product, delivery and corporate pharmacy services in Kibuye, Kampala.", alternates: { canonical: "/services" } };

export default function ServicesPage() {
  const productWa = whatsappHref("Hello Bweza Pharmacy, I would like help with a product or medication enquiry.");
  const deliveryWa = whatsappHref("Hello Bweza Pharmacy, I would like to ask about delivery. My location is [town/district] and I need [product or prescription details].");
  return <><PageHero eyebrow="Pharmacy services" title="Pharmacy services in Kibuye." description="Products, prescriptions, delivery and business supply." /><section className="section"><div className="container"><div className="grid-4"><article className="card"><div className="icon-box">Rx</div><h2 style={{fontSize:"1.2rem"}}>Prescription enquiries</h2><p>Send a valid prescription for pharmacist review.</p><Link href="/prescription" className="card-link">Start prescription review →</Link></article><article className="card"><div className="icon-box">i</div><h2 style={{fontSize:"1.2rem"}}>Product and medication support</h2><p>Ask about products, stock and medicine information.</p><a href={productWa} className="card-link" target={isExternalWhatsApp ? "_blank" : undefined} rel={isExternalWhatsApp ? "noreferrer" : undefined} data-conversion="whatsapp_click" data-intent="product_support" data-location="services_page">Talk to the team →</a></article><article className="card"><div className="icon-box">UG</div><h2 style={{fontSize:"1.2rem"}}>Delivery enquiries</h2><p>Ask about delivery timing, fees and coverage across Uganda.</p><a href={deliveryWa} className="card-link" target={isExternalWhatsApp ? "_blank" : undefined} rel={isExternalWhatsApp ? "noreferrer" : undefined} data-conversion="whatsapp_click" data-intent="delivery_enquiry" data-location="services_page">Ask about delivery →</a></article><article className="card"><div className="icon-box">B2B</div><h2 style={{fontSize:"1.2rem"}}>Corporate procurement</h2><p>Request medicines, first-aid items and medical supplies for your organisation.</p><Link href="/corporate" className="card-link">Request a quotation →</Link></article></div><div className="notice" style={{marginTop:30}}><strong>Health notice:</strong> Website information and online enquiries do not diagnose illness or replace an assessment by a qualified health professional. For an emergency, contact local emergency services or go to the nearest appropriate health facility.</div></div></section><CtaBand /></>;
}
