import type { Metadata } from "next";
import Link from "next/link";
import { PageHero } from "@/components/page-hero";
import { CtaBand } from "@/components/cta-band";
import { isExternalWhatsApp, whatsappHref } from "@/lib/site";

export const metadata: Metadata = { title: "Pharmacy Services", description: "Learn about verified pharmacy and health enquiry services at Bweza Pharmacy in Kibuye, Kampala.", alternates: { canonical: "/services" } };

export default function ServicesPage() {
  const productWa = whatsappHref("Hello Bweza Pharmacy, I would like help with a product or medication enquiry.");
  return <><PageHero eyebrow="Pharmacy services" title="Practical support for everyday health needs." description="Start with an enquiry and our pharmacy team will explain availability, preparation requirements and the appropriate next step." /><section className="section"><div className="container"><div className="grid-3"><article className="card"><div className="icon-box">Rx</div><h2 style={{fontSize:"1.2rem"}}>Prescription enquiries</h2><p>Submit an enquiry for review. A clear, valid prescription may be required before medicine can be supplied.</p><Link href="/prescription" className="card-link">Send a prescription inquiry →</Link></article><article className="card"><div className="icon-box">+</div><h2 style={{fontSize:"1.2rem"}}>General body screening</h2><p>Learn about the UGX 60,000 screening service, confirm availability and ask how to prepare before visiting.</p><Link href="/screening" className="card-link">View screening details →</Link></article><article className="card"><div className="icon-box">i</div><h2 style={{fontSize:"1.2rem"}}>Product and medication support</h2><p>Ask the team about product availability, directions provided with your medicine and when further professional care may be appropriate.</p><a href={productWa} className="card-link" target={isExternalWhatsApp ? "_blank" : undefined} rel={isExternalWhatsApp ? "noreferrer" : undefined} data-conversion="whatsapp_click" data-intent="product_support" data-location="services_page">Talk to the team →</a></article></div><div className="notice" style={{marginTop:30}}><strong>Health notice:</strong> Website information and online enquiries do not diagnose illness or replace an assessment by a qualified health professional. For an emergency, contact local emergency services or go to the nearest appropriate health facility.</div></div></section><CtaBand /></>;
}
