import Image from "next/image";
import Link from "next/link";
import { Arrow, Building, Message, Phone, Search, Upload } from "@/components/icons";
import { CtaBand } from "@/components/cta-band";
import { isExternalWhatsApp, phoneHref, whatsappHref } from "@/lib/site";

const categories = [
  ["Rx", "Prescription medicines", "Send an enquiry for review by the pharmacy team."],
  ["+", "First aid", "Everyday first-aid supplies for homes and workplaces."],
  ["V", "Vitamins & supplements", "Browse wellness-support categories and ask about availability."],
  ["M", "Medical supplies", "Practical health supplies and devices for personal or organisational needs."],
];

export default function Home() {
  const wa = whatsappHref("Hello Bweza Pharmacy, I would like to ask about a product or service.");
  return <>
    <section className="hero"><div className="container hero-grid"><div className="hero-copy"><p className="eyebrow">Your neighbourhood pharmacy in Kibuye</p><h1 className="display">Pharmacy support that puts <span>your needs first.</span></h1><p className="lead">Talk to Bweza Pharmacy about medicines, wellness products, health services and reliable medical-supply enquiries for individuals and organisations in Kampala.</p><div className="button-row"><a className="button button-magenta" href={wa} target={isExternalWhatsApp ? "_blank" : undefined} rel={isExternalWhatsApp ? "noreferrer" : undefined}><Message /> Order via WhatsApp</a><a className="button" href={phoneHref()}><Phone /> Call pharmacy</a><Link className="button button-secondary" href="/products"><Search /> Browse categories</Link></div><div className="trust-inline"><span><i>✓</i> Clear next steps</span><span><i>✓</i> Individual & corporate enquiries</span><span><i>✓</i> Based in Kampala</span></div></div><div className="hero-visual"><div className="hero-photo"><Image src="/images/pharmacy-interior-wide.jpg" alt="Inside Bweza Pharmacy in Kibuye, Kampala" fill sizes="(max-width: 1000px) 100vw, 46vw" priority /></div><div className="hero-card"><strong>A real local pharmacy</strong><p>Explore our categories online, then contact the team to confirm availability and the appropriate next step.</p></div></div></div></section>

    <section className="section"><div className="container"><div className="section-head"><div><p className="eyebrow">What are you looking for?</p><h2 className="heading">A simpler way to start your <span>pharmacy enquiry.</span></h2></div><p className="lead">Browse key categories, then speak with the pharmacy team to confirm suitability and availability.</p></div><div className="grid-4">{categories.map(([icon,title,text])=><article className="card category-card" key={title}><div className="icon-box">{icon}</div><h3>{title}</h3><p>{text}</p><Link href="/products" className="card-link">Explore category →</Link></article>)}</div></div></section>

    <section className="section section-soft"><div className="container split"><div className="photo-stack"><div className="photo-main"><Image src="/images/pharmacy-interior.jpg" alt="Bweza Pharmacy shelves and service counter" fill sizes="(max-width: 1000px) 90vw, 46vw" /></div><div className="photo-small"><Image src="/images/pharmacy-shelves.jpg" alt="Health and wellness products displayed at Bweza Pharmacy" fill sizes="(max-width: 680px) 45vw, 24vw" /></div></div><div><p className="eyebrow">Support for everyday health needs</p><h2 className="heading">Human service, with <span>convenient digital access.</span></h2><p className="lead">Our website helps you find the right route—product enquiry, prescription review, health service or corporate supply request—before speaking with the team.</p><ul className="check-list"><li><b>01</b><span><strong>Product enquiries</strong><br />Ask about medicine, wellness, personal-care and medical-supply categories.</span></li><li><b>02</b><span><strong>Prescription enquiries</strong><br />Use a private submission route or contact the team through WhatsApp.</span></li><li><b>03</b><span><strong>Health screening</strong><br />Enquire about available screening services and preparation requirements.</span></li></ul><div className="button-row"><Link className="button" href="/services">View pharmacy services <Arrow /></Link></div></div></div></section>

    <section className="section"><div className="container"><div className="section-head"><div><p className="eyebrow">Choose your next step</p><h2 className="heading">Built around how customers <span>actually need help.</span></h2></div></div><div className="grid-3"><article className="card"><div className="icon-box"><Message /></div><h3>Talk to our pharmacy team</h3><p>Ask about product availability or the most appropriate way to proceed.</p><a href={wa} className="card-link" target={isExternalWhatsApp ? "_blank" : undefined} rel={isExternalWhatsApp ? "noreferrer" : undefined}>Start a WhatsApp enquiry →</a></article><article className="card"><div className="icon-box"><Upload /></div><h3>Send a prescription inquiry</h3><p>Share contact details and, once configured, upload a clear prescription securely for review.</p><Link href="/prescription" className="card-link">Go to prescription inquiry →</Link></article><article className="card"><div className="icon-box"><Building /></div><h3>Request corporate supply</h3><p>Tell us what your organisation needs and request a quotation through our B2B route.</p><Link href="/corporate" className="card-link">Explore procurement →</Link></article></div></div></section>

    <section className="section section-soft"><div className="container split"><div><p className="eyebrow">Corporate procurement</p><h2 className="heading">A clear supply route for <span>organisations.</span></h2><p className="lead">Bweza Pharmacy welcomes enquiries from companies, clinics, NGOs, schools, construction teams, oil and gas contractors, and other organisations seeking pharmaceutical or medical supplies.</p><ul className="check-list"><li><b>✓</b><span>Structured request-for-quotation process</span></li><li><b>✓</b><span>Medicine, first-aid and medical-supply enquiries</span></li><li><b>✓</b><span>Clear contact and requirement-capture workflow</span></li></ul><div className="button-row"><Link className="button button-magenta" href="/corporate">Request a quote <Arrow /></Link></div></div><div className="photo-main" style={{position:"relative", inset:"auto", minHeight:430}}><Image src="/images/pharmacy-counter.jpg" alt="Bweza Pharmacy product shelves and dispensing counter" fill sizes="(max-width: 1000px) 100vw, 46vw" /></div></div></section>
    <CtaBand />
  </>;
}
