import type { Metadata } from "next";
import { PageHero } from "@/components/page-hero";
import { GoogleEnquiryForm } from "@/components/google-enquiry-form";
import { isExternalWhatsApp, whatsappHref } from "@/lib/site";

export const metadata: Metadata = { title: "Corporate Procurement", description: "Request a quotation for pharmaceutical, first-aid and medical supplies from Bweza Pharmacy in Kampala.", alternates: { canonical: "/corporate" } };

const buyers=["Companies","Clinics & healthcare facilities","NGOs & community programmes","Schools & institutions","Construction teams","Oil & gas contractors"];

export default function CorporatePage(){
  const wa = whatsappHref("Hello Bweza Pharmacy, I am requesting a corporate quotation. Organisation: [name]. Items and quantities: [list]. Required date: [date]. Delivery location: [location].");
  return <><PageHero eyebrow="Corporate procurement" title="A professional route for medical-supply enquiries." description="Bweza Pharmacy welcomes clear requests from organisations seeking medicines, first-aid items, wellness products and medical supplies. Submit your requirements so the team can assess availability and prepare a response." /><section className="section"><div className="container"><div className="section-head"><div><p className="eyebrow">Who we can hear from</p><h2 className="heading">Procurement support across <span>multiple sectors.</span></h2></div><p className="lead">We do not publish unverified client claims. Each request is assessed on its own requirements, quantities and timeline.</p></div><div className="grid-3">{buyers.map((x,i)=><article className="card" key={x}><div className="icon-box">{String(i+1).padStart(2,"0")}</div><h3>{x}</h3><p>Share a detailed requirement list so availability, specifications and quotation terms can be reviewed.</p></article>)}</div></div></section><section className="section section-soft"><div className="container form-shell"><div><p className="eyebrow">Request for quotation</p><h2 className="heading" style={{fontSize:"clamp(2rem,3.5vw,3rem)"}}>Tell us exactly <span>what you need.</span></h2><p className="lead">For a more useful response, include item names or specifications, quantities, delivery location and required date.</p><div className="steps"><div className="step"><strong>Submit requirements</strong><p>Provide an itemised description or summary of your supply needs.</p></div><div className="step"><strong>Requirement review</strong><p>The pharmacy team clarifies specifications and checks possible availability.</p></div><div className="step"><strong>Quotation response</strong><p>If the request can be supported, the team provides the next commercial steps.</p></div></div><div className="button-row"><a className="button button-magenta" href={wa} target={isExternalWhatsApp ? "_blank" : undefined} rel={isExternalWhatsApp ? "noreferrer" : undefined} data-conversion="corporate_enquiry" data-intent="corporate_quotation" data-location="corporate_page">Send requirements on WhatsApp</a></div></div><GoogleEnquiryForm context="corporate" /></div></section></>;
}
